name: metabarcoding-analysis

services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command:
      - sh
      - -c
      - |
        cd /usr/src/pipeline &&
        find ./bin -type f -name '*.py' -exec dos2unix {} \; &&
        find ./templates -type f -name '*.py' -exec dos2unix {} \; &&
        nextflow run main.nf \
          --reads './reads_datasets/*' \
          --db '/usr/src/db/16S_ribosomal_RNA' \
          --tax '/usr/src/db/taxdb/'
    volumes:
      # En development, bindear la carpeta nanoclust entera para ver los cambios en vivo
      - ./nanoclust:/usr/src/pipeline
      # En production, bindear solo las carpetas reads y results y hacer un layer COPY de nanoclust
      - ${READS_PATH}:/usr/src/pipeline/reads_datasets
      - ${RESULTS_PATH}:/usr/src/pipeline/results